[package]
name = "fastnum_examples_competitors"
version = "0.0.1"
authors = ["Neo"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
fastnum = { path = "../../" }
rust_decimal = { version = "1.37.1", features = ["maths"] }